### ISSUE TITLE
Feature Request: Support for Additional Aquacomputer Devices (Aquaero, Farbwerk, MPS, VISION)

### ISSUE THREAD

**Issue by JoshWay** [aleksamagicka/lensors#3]
The following devices are connected but not recognized by liquidctl. Here are the details for each, including Vendor ID and Product ID:

    Aquaero (Fan controller and monitoring device)
        Vendor ID: 0c70
        Product ID: f001
        Description: Provides advanced fan control, monitoring for temperature sensors, flow meters, and more. It’s a central component for custom water-cooling setups.

    Farbwerk (RGB lighting controller)
        Vendor ID: 0c70
        Product ID: f00a
        Description: Manages RGB lighting for connected LEDs and strips. It would be beneficial for liquidctl to control lighting effects and synchronization.

    MPS (Flow and pressure sensor)
        Vendor ID: 0c70
        Product ID: f003
        Description: Monitors water flow and pressure within the cooling loop. Adding support for this device would allow monitoring flow rates directly within liquidctl.

    VISION (Display and monitoring device)
        Vendor ID: 0c70
        Product ID: f00c
        Description: An external display that shows various system stats, often mounted inside the case. This device allows real-time monitoring and display of key parameters.

Debug Information

I’ve run liquidctl --debug list to provide detailed logs. Here’s a summary of the relevant debug information:

    Aquacomputer D5 Next devices are detected and fully supported by liquidctl.
    Unrecognized devices: Despite showing up on the USB bus (0c70:f001, 0c70:f00a, 0c70:f003, 0c70:f00c), these devices are not identified as controllable hardware within liquidctl.

Sample debug output:

HID device: 0c70:f003 (usage_page=0xff00 usage=0x0001)  # MPS
HID device: 0c70:f00a (usage_page=0xff00 usage=0x0001)  # Farbwerk
HID device: 0c70:f001 (usage_page=0xff00 usage=0x0001)  # Aquaero
HID device: 0c70:f00c (usage_page=0xff00 usage=0x0001)  # VISION

Additional Information

    OS: Linux (kernel version 6.11.6-zen1-1-zen, x86_64)
    Python version: 3.12.7
    liquidctl version: 1.14.0.dev91+gb3913d0
    Relevant libraries: pyusb, hidapi, smbus, and others are installed and up to date.

**Comment by aleksamagicka** [comment]
First time I've received an LLM generated blob for anything on Github... Typing up a few sentences would have been just fine 😒 

Anyway, no can do for now because:

- This is not the right repo for that (_please_, watch where you're posting)
- I don't really have the time for that right now

And I find `Purpose and Benefits` funny - you don't need to convince someone who started the Aquacomputer movement on Linux to develop support for a device...

**Comment by JoshWay** [comment]
Yeah I know… sorry man.  I wasn't actually trying to be normie.  I just couldn't explain it the way I wanted to and was in a hurry because I had to get onto some other work… so I blobbed!

I just figured you'd cring out and get the point and be like, "yes or not right now, or not ever!".

* This is not the right repo for that ( please , watch where you're posting)

    Oh?  I was using Lensors to accomplish this work.  I though this was the right place.

* I don't really have the time for that right now

    Totally understood.  I'm not a programmer (clearly), so just asking on behalf of myself and anyone that might like support for further devices.

Thanks for the quick reply!

**Comment by JoshWay** [comment]
Fixed the orginial request to only the useful things.
